// ProjectionRoom 线上协议（唯一真源）。
//
// 约定：
//   - 本文件是客户端与服务器之间**所有**控制消息的唯一真源，改字段先改这里再重新生成；
//   - 视频分片数据不经 protobuf：它走 DataChannel 的原始二进制帧（8 字节头 + fMP4 片段），
//     包一层只会平白多一次大块内存拷贝；
//   - type / role / action / code 用 string 而不是 enum：它们是开放集合，
//     用字符串能让日志、前端调试与向后兼容都简单一档。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0--rc2
// source: projection_room.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MediaSegment 是一个媒体分片（与 internal/model.Segment 一一对应）。
type MediaSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 从 1 开始；0 保留给 init 段
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Duration      float64                `protobuf:"fixed64,5,opt,name=duration,proto3" json:"duration,omitempty"`
	StartPts      float64                `protobuf:"fixed64,6,opt,name=start_pts,json=startPts,proto3" json:"start_pts,omitempty"`
	Keyframe      bool                   `protobuf:"varint,7,opt,name=keyframe,proto3" json:"keyframe,omitempty"`
	Sha256        string                 `protobuf:"bytes,8,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaSegment) Reset() {
	*x = MediaSegment{}
	mi := &file_projection_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSegment) ProtoMessage() {}

func (x *MediaSegment) ProtoReflect() protoreflect.Message {
	mi := &file_projection_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSegment.ProtoReflect.Descriptor instead.
func (*MediaSegment) Descriptor() ([]byte, []int) {
	return file_projection_room_proto_rawDescGZIP(), []int{0}
}

func (x *MediaSegment) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MediaSegment) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *MediaSegment) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MediaSegment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MediaSegment) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MediaSegment) GetStartPts() float64 {
	if x != nil {
		return x.StartPts
	}
	return 0
}

func (x *MediaSegment) GetKeyframe() bool {
	if x != nil {
		return x.Keyframe
	}
	return false
}

func (x *MediaSegment) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// MediaIndex 是主播发布的分片索引。
type MediaIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	InitFile      string                 `protobuf:"bytes,2,opt,name=init_file,json=initFile,proto3" json:"init_file,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	TotalDuration float64                `protobuf:"fixed64,4,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"`
	SegmentSec    float64                `protobuf:"fixed64,5,opt,name=segment_sec,json=segmentSec,proto3" json:"segment_sec,omitempty"`
	BitrateBps    int64                  `protobuf:"varint,6,opt,name=bitrate_bps,json=bitrateBps,proto3" json:"bitrate_bps,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,7,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Segments      []*MediaSegment        `protobuf:"bytes,8,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaIndex) Reset() {
	*x = MediaIndex{}
	mi := &file_projection_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaIndex) ProtoMessage() {}

func (x *MediaIndex) ProtoReflect() protoreflect.Message {
	mi := &file_projection_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaIndex.ProtoReflect.Descriptor instead.
func (*MediaIndex) Descriptor() ([]byte, []int) {
	return file_projection_room_proto_rawDescGZIP(), []int{1}
}

func (x *MediaIndex) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MediaIndex) GetInitFile() string {
	if x != nil {
		return x.InitFile
	}
	return ""
}

func (x *MediaIndex) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaIndex) GetTotalDuration() float64 {
	if x != nil {
		return x.TotalDuration
	}
	return 0
}

func (x *MediaIndex) GetSegmentSec() float64 {
	if x != nil {
		return x.SegmentSec
	}
	return 0
}

func (x *MediaIndex) GetBitrateBps() int64 {
	if x != nil {
		return x.BitrateBps
	}
	return 0
}

func (x *MediaIndex) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MediaIndex) GetSegments() []*MediaSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

// PlaybackState 是播放权威信息。主播是唯一时间源，中继只转发不改写。
type PlaybackState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paused        bool                   `protobuf:"varint,1,opt,name=paused,proto3" json:"paused,omitempty"`
	CurrentTime   float64                `protobuf:"fixed64,2,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	HostClockMs   int64                  `protobuf:"varint,3,opt,name=host_clock_ms,json=hostClockMs,proto3" json:"host_clock_ms,omitempty"` // 主播单调时钟读数
	Rate          float64                `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`
	Seq           int64                  `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`                                // 单调递增，乱序/重复一律丢弃
	ClockEpoch    string                 `protobuf:"bytes,6,opt,name=clock_epoch,json=clockEpoch,proto3" json:"clock_epoch,omitempty"` // 主播页面时钟纪元；变化即重置偏移滤波
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackState) Reset() {
	*x = PlaybackState{}
	mi := &file_projection_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackState) ProtoMessage() {}

func (x *PlaybackState) ProtoReflect() protoreflect.Message {
	mi := &file_projection_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackState.ProtoReflect.Descriptor instead.
func (*PlaybackState) Descriptor() ([]byte, []int) {
	return file_projection_room_proto_rawDescGZIP(), []int{2}
}

func (x *PlaybackState) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *PlaybackState) GetCurrentTime() float64 {
	if x != nil {
		return x.CurrentTime
	}
	return 0
}

func (x *PlaybackState) GetHostClockMs() int64 {
	if x != nil {
		return x.HostClockMs
	}
	return 0
}

func (x *PlaybackState) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *PlaybackState) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PlaybackState) GetClockEpoch() string {
	if x != nil {
		return x.ClockEpoch
	}
	return ""
}

// Metrics 是成员上报的实测度量。
type Metrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RttMs             float64                `protobuf:"fixed64,1,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	ThroughputBps     float64                `protobuf:"fixed64,2,opt,name=throughput_bps,json=throughputBps,proto3" json:"throughput_bps,omitempty"`
	UploadCapacityBps int64                  `protobuf:"varint,3,opt,name=upload_capacity_bps,json=uploadCapacityBps,proto3" json:"upload_capacity_bps,omitempty"`
	Depth             int32                  `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	// 以下用于"卡顿 → 重算路径"：健康度恶化时客户端主动上报，服务器据此重排拓扑。
	BufferHealth  float64 `protobuf:"fixed64,5,opt,name=buffer_health,json=bufferHealth,proto3" json:"buffer_health,omitempty"`      // 已就绪缓冲秒数 / 目标缓冲秒数，0-1
	P95DeliveryMs float64 `protobuf:"fixed64,6,opt,name=p95_delivery_ms,json=p95DeliveryMs,proto3" json:"p95_delivery_ms,omitempty"` // 最近分片交付 p95
	StallCount    int32   `protobuf:"varint,7,opt,name=stall_count,json=stallCount,proto3" json:"stall_count,omitempty"`
	Degraded      bool    `protobuf:"varint,8,opt,name=degraded,proto3" json:"degraded,omitempty"`                   // 自评"我现在拖后腿了"
	PrimaryId     string  `protobuf:"bytes,9,opt,name=primary_id,json=primaryId,proto3" json:"primary_id,omitempty"` // 当前主父，便于服务器判断是不是上游的问题
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_projection_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_projection_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_projection_room_proto_rawDescGZIP(), []int{3}
}

func (x *Metrics) GetRttMs() float64 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *Metrics) GetThroughputBps() float64 {
	if x != nil {
		return x.ThroughputBps
	}
	return 0
}

func (x *Metrics) GetUploadCapacityBps() int64 {
	if x != nil {
		return x.UploadCapacityBps
	}
	return 0
}

func (x *Metrics) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Metrics) GetBufferHealth() float64 {
	if x != nil {
		return x.BufferHealth
	}
	return 0
}

func (x *Metrics) GetP95DeliveryMs() float64 {
	if x != nil {
		return x.P95DeliveryMs
	}
	return 0
}

func (x *Metrics) GetStallCount() int32 {
	if x != nil {
		return x.StallCount
	}
	return 0
}

func (x *Metrics) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *Metrics) GetPrimaryId() string {
	if x != nil {
		return x.PrimaryId
	}
	return ""
}

// MemberInfo 是成员列表条目。
type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Depth         int32                  `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	PrimaryId     string                 `protobuf:"bytes,5,opt,name=primary_id,json=primaryId,proto3" json:"primary_id,omitempty"`
	BackupIds     []string               `protobuf:"bytes,6,rep,name=backup_ids,json=backupIds,proto3" json:"backup_ids,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,7,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_projection_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_projection_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_projection_room_proto_rawDescGZIP(), []int{4}
}

func (x *MemberInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemberInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MemberInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MemberInfo) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *MemberInfo) GetPrimaryId() string {
	if x != nil {
		return x.PrimaryId
	}
	return ""
}

func (x *MemberInfo) GetBackupIds() []string {
	if x != nil {
		return x.BackupIds
	}
	return nil
}

func (x *MemberInfo) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

// Capacity 是房间容量判断。
type Capacity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mode           string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	MaxMembers     int32                  `protobuf:"varint,2,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"`
	StreamBps      int64                  `protobuf:"varint,3,opt,name=stream_bps,json=streamBps,proto3" json:"stream_bps,omitempty"`
	HostChildSlots int32                  `protobuf:"varint,4,opt,name=host_child_slots,json=hostChildSlots,proto3" json:"host_child_slots,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Capacity) Reset() {
	*x = Capacity{}
	mi := &file_projection_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capacity) ProtoMessage() {}

func (x *Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_projection_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capacity.ProtoReflect.Descriptor instead.
func (*Capacity) Descriptor() ([]byte, []int) {
	return file_projection_room_proto_rawDescGZIP(), []int{5}
}

func (x *Capacity) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Capacity) GetMaxMembers() int32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

func (x *Capacity) GetStreamBps() int64 {
	if x != nil {
		return x.StreamBps
	}
	return 0
}

func (x *Capacity) GetHostChildSlots() int32 {
	if x != nil {
		return x.HostChildSlots
	}
	return 0
}

// TopologyAssignment 是一个节点在分发树中的位置。
type TopologyAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PrimaryId     string                 `protobuf:"bytes,2,opt,name=primary_id,json=primaryId,proto3" json:"primary_id,omitempty"`
	BackupIds     []string               `protobuf:"bytes,3,rep,name=backup_ids,json=backupIds,proto3" json:"backup_ids,omitempty"`
	Children      []string               `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"` // 以本节点为主父的成员：进度沿这条路径逐跳转发
	Depth         int32                  `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	DistributorId string                 `protobuf:"bytes,7,opt,name=distributor_id,json=distributorId,proto3" json:"distributor_id,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	MaxDepth      int32                  `protobuf:"varint,9,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyAssignment) Reset() {
	*x = TopologyAssignment{}
	mi := &file_projection_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyAssignment) ProtoMessage() {}

func (x *TopologyAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_projection_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyAssignment.ProtoReflect.Descriptor instead.
func (*TopologyAssignment) Descriptor() ([]byte, []int) {
	return file_projection_room_proto_rawDescGZIP(), []int{6}
}

func (x *TopologyAssignment) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *TopologyAssignment) GetPrimaryId() string {
	if x != nil {
		return x.PrimaryId
	}
	return ""
}

func (x *TopologyAssignment) GetBackupIds() []string {
	if x != nil {
		return x.BackupIds
	}
	return nil
}

func (x *TopologyAssignment) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *TopologyAssignment) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *TopologyAssignment) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *TopologyAssignment) GetDistributorId() string {
	if x != nil {
		return x.DistributorId
	}
	return ""
}

func (x *TopologyAssignment) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TopologyAssignment) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

// DistributorChange 是单链模式下分发节点的换防通知。
type DistributorChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributorChange) Reset() {
	*x = DistributorChange{}
	mi := &file_projection_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributorChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributorChange) ProtoMessage() {}

func (x *DistributorChange) ProtoReflect() protoreflect.Message {
	mi := &file_projection_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributorChange.ProtoReflect.Descriptor instead.
func (*DistributorChange) Descriptor() ([]byte, []int) {
	return file_projection_room_proto_rawDescGZIP(), []int{7}
}

func (x *DistributorChange) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *DistributorChange) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *DistributorChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Envelope 是 WebSocket 上的统一信封。
type Envelope struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Type        string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	RoomId      string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId    string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	To          string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	From        string                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	DisplayName string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Role        string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	Password    string                 `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	Payload     []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"` // SDP / ICE 原样透传
	Text        string                 `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`
	Ts          int64                  `protobuf:"varint,11,opt,name=ts,proto3" json:"ts,omitempty"`
	// 客户端上行：房主控制意图
	Action      string  `protobuf:"bytes,12,opt,name=action,proto3" json:"action,omitempty"`
	CurrentTime float64 `protobuf:"fixed64,13,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	HostClockMs int64   `protobuf:"varint,14,opt,name=host_clock_ms,json=hostClockMs,proto3" json:"host_clock_ms,omitempty"`
	ClockEpoch  string  `protobuf:"bytes,15,opt,name=clock_epoch,json=clockEpoch,proto3" json:"clock_epoch,omitempty"`
	Paused      bool    `protobuf:"varint,16,opt,name=paused,proto3" json:"paused,omitempty"`
	Rate        float64 `protobuf:"fixed64,17,opt,name=rate,proto3" json:"rate,omitempty"`
	// 服务端下行：播放权威信息
	Playback    *PlaybackState      `protobuf:"bytes,18,opt,name=playback,proto3" json:"playback,omitempty"`
	Seq         int64               `protobuf:"varint,19,opt,name=seq,proto3" json:"seq,omitempty"`
	Metrics     *Metrics            `protobuf:"bytes,20,opt,name=metrics,proto3" json:"metrics,omitempty"`
	SelfId      string              `protobuf:"bytes,21,opt,name=self_id,json=selfId,proto3" json:"self_id,omitempty"`
	HostId      string              `protobuf:"bytes,22,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Member      *MemberInfo         `protobuf:"bytes,23,opt,name=member,proto3" json:"member,omitempty"`
	Members     []*MemberInfo       `protobuf:"bytes,24,rep,name=members,proto3" json:"members,omitempty"`
	MediaIndex  *MediaIndex         `protobuf:"bytes,25,opt,name=media_index,json=mediaIndex,proto3" json:"media_index,omitempty"`
	Capacity    *Capacity           `protobuf:"bytes,26,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Topology    *TopologyAssignment `protobuf:"bytes,27,opt,name=topology,proto3" json:"topology,omitempty"`
	Distributor *DistributorChange  `protobuf:"bytes,28,opt,name=distributor,proto3" json:"distributor,omitempty"`
	// 分片拥有位图（原先是 base64 字符串；改成 bytes 省掉一次编解码与 33% 体积）
	Have     []byte `protobuf:"bytes,29,opt,name=have,proto3" json:"have,omitempty"`
	Complete bool   `protobuf:"varint,30,opt,name=complete,proto3" json:"complete,omitempty"`
	Code     string `protobuf:"bytes,31,opt,name=code,proto3" json:"code,omitempty"`
	Message  string `protobuf:"bytes,32,opt,name=message,proto3" json:"message,omitempty"`
	// 请求/通知的缘由（如 topology-request 的 "stalled"、换防原因）
	Reason        string `protobuf:"bytes,33,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_projection_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_projection_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_projection_room_proto_rawDescGZIP(), []int{8}
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Envelope) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Envelope) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Envelope) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Envelope) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Envelope) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Envelope) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Envelope) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Envelope) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Envelope) GetCurrentTime() float64 {
	if x != nil {
		return x.CurrentTime
	}
	return 0
}

func (x *Envelope) GetHostClockMs() int64 {
	if x != nil {
		return x.HostClockMs
	}
	return 0
}

func (x *Envelope) GetClockEpoch() string {
	if x != nil {
		return x.ClockEpoch
	}
	return ""
}

func (x *Envelope) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *Envelope) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Envelope) GetPlayback() *PlaybackState {
	if x != nil {
		return x.Playback
	}
	return nil
}

func (x *Envelope) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Envelope) GetSelfId() string {
	if x != nil {
		return x.SelfId
	}
	return ""
}

func (x *Envelope) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Envelope) GetMember() *MemberInfo {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *Envelope) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Envelope) GetMediaIndex() *MediaIndex {
	if x != nil {
		return x.MediaIndex
	}
	return nil
}

func (x *Envelope) GetCapacity() *Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *Envelope) GetTopology() *TopologyAssignment {
	if x != nil {
		return x.Topology
	}
	return nil
}

func (x *Envelope) GetDistributor() *DistributorChange {
	if x != nil {
		return x.Distributor
	}
	return nil
}

func (x *Envelope) GetHave() []byte {
	if x != nil {
		return x.Have
	}
	return nil
}

func (x *Envelope) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *Envelope) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Envelope) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Envelope) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PeerControl 是 DataChannel 上的控制消息。
// 分片数据本身不走这里：它在控制消息之后以原始二进制帧发送。
type PeerControl struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	T        string                 `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"` // req | chunk | err | have | ping | pong | progress | time-sync
	Rid      string                 `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Idx      int32                  `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	Code     string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Chunks   []byte                 `protobuf:"bytes,5,opt,name=chunks,proto3" json:"chunks,omitempty"` // have 位图
	Complete bool                   `protobuf:"varint,6,opt,name=complete,proto3" json:"complete,omitempty"`
	Ts       int64                  `protobuf:"varint,7,opt,name=ts,proto3" json:"ts,omitempty"`
	// progress / time-sync
	CurrentTime float64 `protobuf:"fixed64,8,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	HostClockMs int64   `protobuf:"varint,9,opt,name=host_clock_ms,json=hostClockMs,proto3" json:"host_clock_ms,omitempty"`
	ClockEpoch  string  `protobuf:"bytes,10,opt,name=clock_epoch,json=clockEpoch,proto3" json:"clock_epoch,omitempty"`
	Paused      bool    `protobuf:"varint,11,opt,name=paused,proto3" json:"paused,omitempty"`
	Rate        float64 `protobuf:"fixed64,12,opt,name=rate,proto3" json:"rate,omitempty"`
	Seq         int64   `protobuf:"varint,13,opt,name=seq,proto3" json:"seq,omitempty"`
	// 逐跳时钟中继（解决"多跳叶子稳定滞后 = 路径最小单向延迟"）：
	// 转发节点填入**自己的本地时钟**与**自己到主播的偏移估计**，
	// 子节点据此把"到父的偏移"与"父到主播的偏移"相加，
	// 误差从"整条路径的单向延迟"降到"各跳半 RTT 之和"。
	ParentClockMs  int64   `protobuf:"varint,14,opt,name=parent_clock_ms,json=parentClockMs,proto3" json:"parent_clock_ms,omitempty"`
	ParentOffsetMs float64 `protobuf:"fixed64,15,opt,name=parent_offset_ms,json=parentOffsetMs,proto3" json:"parent_offset_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerControl) Reset() {
	*x = PeerControl{}
	mi := &file_projection_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerControl) ProtoMessage() {}

func (x *PeerControl) ProtoReflect() protoreflect.Message {
	mi := &file_projection_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerControl.ProtoReflect.Descriptor instead.
func (*PeerControl) Descriptor() ([]byte, []int) {
	return file_projection_room_proto_rawDescGZIP(), []int{9}
}

func (x *PeerControl) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

func (x *PeerControl) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *PeerControl) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *PeerControl) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PeerControl) GetChunks() []byte {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *PeerControl) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *PeerControl) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *PeerControl) GetCurrentTime() float64 {
	if x != nil {
		return x.CurrentTime
	}
	return 0
}

func (x *PeerControl) GetHostClockMs() int64 {
	if x != nil {
		return x.HostClockMs
	}
	return 0
}

func (x *PeerControl) GetClockEpoch() string {
	if x != nil {
		return x.ClockEpoch
	}
	return ""
}

func (x *PeerControl) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *PeerControl) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *PeerControl) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PeerControl) GetParentClockMs() int64 {
	if x != nil {
		return x.ParentClockMs
	}
	return 0
}

func (x *PeerControl) GetParentOffsetMs() float64 {
	if x != nil {
		return x.ParentOffsetMs
	}
	return 0
}

var File_projection_room_proto protoreflect.FileDescriptor

const file_projection_room_proto_rawDesc = "" +
	"\n" +
	"\x15projection_room.proto\x12\x12projection_room.v1\"\xd1\x01\n" +
	"\fMediaSegment\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x01R\bduration\x12\x1b\n" +
	"\tstart_pts\x18\x06 \x01(\x01R\bstartPts\x12\x1a\n" +
	"\bkeyframe\x18\a \x01(\bR\bkeyframe\x12\x16\n" +
	"\x06sha256\x18\b \x01(\tR\x06sha256\"\xa8\x02\n" +
	"\n" +
	"MediaIndex\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x1b\n" +
	"\tinit_file\x18\x02 \x01(\tR\binitFile\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12%\n" +
	"\x0etotal_duration\x18\x04 \x01(\x01R\rtotalDuration\x12\x1f\n" +
	"\vsegment_sec\x18\x05 \x01(\x01R\n" +
	"segmentSec\x12\x1f\n" +
	"\vbitrate_bps\x18\x06 \x01(\x03R\n" +
	"bitrateBps\x12\x1f\n" +
	"\vtotal_bytes\x18\a \x01(\x03R\n" +
	"totalBytes\x12<\n" +
	"\bsegments\x18\b \x03(\v2 .projection_room.v1.MediaSegmentR\bsegments\"\xb5\x01\n" +
	"\rPlaybackState\x12\x16\n" +
	"\x06paused\x18\x01 \x01(\bR\x06paused\x12!\n" +
	"\fcurrent_time\x18\x02 \x01(\x01R\vcurrentTime\x12\"\n" +
	"\rhost_clock_ms\x18\x03 \x01(\x03R\vhostClockMs\x12\x12\n" +
	"\x04rate\x18\x04 \x01(\x01R\x04rate\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x03R\x03seq\x12\x1f\n" +
	"\vclock_epoch\x18\x06 \x01(\tR\n" +
	"clockEpoch\"\xb6\x02\n" +
	"\aMetrics\x12\x15\n" +
	"\x06rtt_ms\x18\x01 \x01(\x01R\x05rttMs\x12%\n" +
	"\x0ethroughput_bps\x18\x02 \x01(\x01R\rthroughputBps\x12.\n" +
	"\x13upload_capacity_bps\x18\x03 \x01(\x03R\x11uploadCapacityBps\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\x12#\n" +
	"\rbuffer_health\x18\x05 \x01(\x01R\fbufferHealth\x12&\n" +
	"\x0fp95_delivery_ms\x18\x06 \x01(\x01R\rp95DeliveryMs\x12\x1f\n" +
	"\vstall_count\x18\a \x01(\x05R\n" +
	"stallCount\x12\x1a\n" +
	"\bdegraded\x18\b \x01(\bR\bdegraded\x12\x1d\n" +
	"\n" +
	"primary_id\x18\t \x01(\tR\tprimaryId\"\xc4\x01\n" +
	"\n" +
	"MemberInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\x12\x1d\n" +
	"\n" +
	"primary_id\x18\x05 \x01(\tR\tprimaryId\x12\x1d\n" +
	"\n" +
	"backup_ids\x18\x06 \x03(\tR\tbackupIds\x12\x1b\n" +
	"\tjoined_at\x18\a \x01(\x03R\bjoinedAt\"\x88\x01\n" +
	"\bCapacity\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1f\n" +
	"\vmax_members\x18\x02 \x01(\x05R\n" +
	"maxMembers\x12\x1d\n" +
	"\n" +
	"stream_bps\x18\x03 \x01(\x03R\tstreamBps\x12(\n" +
	"\x10host_child_slots\x18\x04 \x01(\x05R\x0ehostChildSlots\"\x8d\x02\n" +
	"\x12TopologyAssignment\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1d\n" +
	"\n" +
	"primary_id\x18\x02 \x01(\tR\tprimaryId\x12\x1d\n" +
	"\n" +
	"backup_ids\x18\x03 \x03(\tR\tbackupIds\x12\x1a\n" +
	"\bchildren\x18\x04 \x03(\tR\bchildren\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\x05R\x05depth\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12%\n" +
	"\x0edistributor_id\x18\a \x01(\tR\rdistributorId\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x1b\n" +
	"\tmax_depth\x18\t \x01(\x05R\bmaxDepth\"Y\n" +
	"\x11DistributorChange\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xdf\b\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04from\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12\x12\n" +
	"\x04text\x18\n" +
	" \x01(\tR\x04text\x12\x0e\n" +
	"\x02ts\x18\v \x01(\x03R\x02ts\x12\x16\n" +
	"\x06action\x18\f \x01(\tR\x06action\x12!\n" +
	"\fcurrent_time\x18\r \x01(\x01R\vcurrentTime\x12\"\n" +
	"\rhost_clock_ms\x18\x0e \x01(\x03R\vhostClockMs\x12\x1f\n" +
	"\vclock_epoch\x18\x0f \x01(\tR\n" +
	"clockEpoch\x12\x16\n" +
	"\x06paused\x18\x10 \x01(\bR\x06paused\x12\x12\n" +
	"\x04rate\x18\x11 \x01(\x01R\x04rate\x12=\n" +
	"\bplayback\x18\x12 \x01(\v2!.projection_room.v1.PlaybackStateR\bplayback\x12\x10\n" +
	"\x03seq\x18\x13 \x01(\x03R\x03seq\x125\n" +
	"\ametrics\x18\x14 \x01(\v2\x1b.projection_room.v1.MetricsR\ametrics\x12\x17\n" +
	"\aself_id\x18\x15 \x01(\tR\x06selfId\x12\x17\n" +
	"\ahost_id\x18\x16 \x01(\tR\x06hostId\x126\n" +
	"\x06member\x18\x17 \x01(\v2\x1e.projection_room.v1.MemberInfoR\x06member\x128\n" +
	"\amembers\x18\x18 \x03(\v2\x1e.projection_room.v1.MemberInfoR\amembers\x12?\n" +
	"\vmedia_index\x18\x19 \x01(\v2\x1e.projection_room.v1.MediaIndexR\n" +
	"mediaIndex\x128\n" +
	"\bcapacity\x18\x1a \x01(\v2\x1c.projection_room.v1.CapacityR\bcapacity\x12B\n" +
	"\btopology\x18\x1b \x01(\v2&.projection_room.v1.TopologyAssignmentR\btopology\x12G\n" +
	"\vdistributor\x18\x1c \x01(\v2%.projection_room.v1.DistributorChangeR\vdistributor\x12\x12\n" +
	"\x04have\x18\x1d \x01(\fR\x04have\x12\x1a\n" +
	"\bcomplete\x18\x1e \x01(\bR\bcomplete\x12\x12\n" +
	"\x04code\x18\x1f \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18  \x01(\tR\amessage\x12\x16\n" +
	"\x06reason\x18! \x01(\tR\x06reason\"\x8f\x03\n" +
	"\vPeerControl\x12\f\n" +
	"\x01t\x18\x01 \x01(\tR\x01t\x12\x10\n" +
	"\x03rid\x18\x02 \x01(\tR\x03rid\x12\x10\n" +
	"\x03idx\x18\x03 \x01(\x05R\x03idx\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x16\n" +
	"\x06chunks\x18\x05 \x01(\fR\x06chunks\x12\x1a\n" +
	"\bcomplete\x18\x06 \x01(\bR\bcomplete\x12\x0e\n" +
	"\x02ts\x18\a \x01(\x03R\x02ts\x12!\n" +
	"\fcurrent_time\x18\b \x01(\x01R\vcurrentTime\x12\"\n" +
	"\rhost_clock_ms\x18\t \x01(\x03R\vhostClockMs\x12\x1f\n" +
	"\vclock_epoch\x18\n" +
	" \x01(\tR\n" +
	"clockEpoch\x12\x16\n" +
	"\x06paused\x18\v \x01(\bR\x06paused\x12\x12\n" +
	"\x04rate\x18\f \x01(\x01R\x04rate\x12\x10\n" +
	"\x03seq\x18\r \x01(\x03R\x03seq\x12&\n" +
	"\x0fparent_clock_ms\x18\x0e \x01(\x03R\rparentClockMs\x12(\n" +
	"\x10parent_offset_ms\x18\x0f \x01(\x01R\x0eparentOffsetMsB\x1fZ\x1dProjectionRoom/internal/pb;pbb\x06proto3"

var (
	file_projection_room_proto_rawDescOnce sync.Once
	file_projection_room_proto_rawDescData []byte
)

func file_projection_room_proto_rawDescGZIP() []byte {
	file_projection_room_proto_rawDescOnce.Do(func() {
		file_projection_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_projection_room_proto_rawDesc), len(file_projection_room_proto_rawDesc)))
	})
	return file_projection_room_proto_rawDescData
}

var file_projection_room_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_projection_room_proto_goTypes = []any{
	(*MediaSegment)(nil),       // 0: projection_room.v1.MediaSegment
	(*MediaIndex)(nil),         // 1: projection_room.v1.MediaIndex
	(*PlaybackState)(nil),      // 2: projection_room.v1.PlaybackState
	(*Metrics)(nil),            // 3: projection_room.v1.Metrics
	(*MemberInfo)(nil),         // 4: projection_room.v1.MemberInfo
	(*Capacity)(nil),           // 5: projection_room.v1.Capacity
	(*TopologyAssignment)(nil), // 6: projection_room.v1.TopologyAssignment
	(*DistributorChange)(nil),  // 7: projection_room.v1.DistributorChange
	(*Envelope)(nil),           // 8: projection_room.v1.Envelope
	(*PeerControl)(nil),        // 9: projection_room.v1.PeerControl
}
var file_projection_room_proto_depIdxs = []int32{
	0, // 0: projection_room.v1.MediaIndex.segments:type_name -> projection_room.v1.MediaSegment
	2, // 1: projection_room.v1.Envelope.playback:type_name -> projection_room.v1.PlaybackState
	3, // 2: projection_room.v1.Envelope.metrics:type_name -> projection_room.v1.Metrics
	4, // 3: projection_room.v1.Envelope.member:type_name -> projection_room.v1.MemberInfo
	4, // 4: projection_room.v1.Envelope.members:type_name -> projection_room.v1.MemberInfo
	1, // 5: projection_room.v1.Envelope.media_index:type_name -> projection_room.v1.MediaIndex
	5, // 6: projection_room.v1.Envelope.capacity:type_name -> projection_room.v1.Capacity
	6, // 7: projection_room.v1.Envelope.topology:type_name -> projection_room.v1.TopologyAssignment
	7, // 8: projection_room.v1.Envelope.distributor:type_name -> projection_room.v1.DistributorChange
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_projection_room_proto_init() }
func file_projection_room_proto_init() {
	if File_projection_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projection_room_proto_rawDesc), len(file_projection_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_projection_room_proto_goTypes,
		DependencyIndexes: file_projection_room_proto_depIdxs,
		MessageInfos:      file_projection_room_proto_msgTypes,
	}.Build()
	File_projection_room_proto = out.File
	file_projection_room_proto_goTypes = nil
	file_projection_room_proto_depIdxs = nil
}
