// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ProjectionRoom/internal/bootstrap"
	"ProjectionRoom/internal/config"
	"ProjectionRoom/internal/service"
	"ProjectionRoom/internal/service/segment"
)

// Injectors from wire.go:

// InitializeApp 组装整条依赖链并返回可运行的服务（cmd 里没有业务，只有装配与启动）。
//
// 依赖链的**声明**在 internal/bootstrap.ProviderSet：**provider 的书写顺序即创建
// 顺序，而清理按创建顺序的反序执行**，因此"服务先停 → flush 事件写队列 → 关连接池"
// 这段顺序语义与 ProviderSet 的注释放在一起（本文件只负责把它接进来）。
//
// 生成结果 cmd/wire_gen.go 由 `go tool wire ./cmd` 产出，不要手写；
// 改动 ProviderSet 的顺序之后必须重新生成，并逐行核对 wire_gen.go 里 cleanup 的序列。
func InitializeApp(cfg *config.Config) (*service.Server, func(), error) {
	hub, cleanup, err := service.NewHub(cfg)
	if err != nil {
		return nil, nil, err
	}
	broadcaster := service.NewBroadcaster(hub)
	manager := service.NewManager(cfg, broadcaster)
	queue, cleanup2, err := segment.NewQueue(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dbResources, cleanup3, err := bootstrap.NewDBResources(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	accountStoreAdapter, err := bootstrap.NewAccountStore(dbResources)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	signer, err := bootstrap.NewSigner(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ticketStore := bootstrap.NewTicketStore(cfg)
	accountService, err := bootstrap.NewAccountService(cfg, accountStoreAdapter, signer, ticketStore)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authDeps, err := bootstrap.NewEngineDeps(cfg, dbResources, accountService, ticketStore)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	logRingResources, cleanup4, err := bootstrap.NewLogRingResources(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	adminDeps, err := bootstrap.NewAdminDeps(cfg, dbResources, accountService, hub, manager, logRingResources)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	engine, err := bootstrap.NewEngine(cfg, hub, manager, queue, authDeps, adminDeps)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server, err := service.NewServer(cfg, engine)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
