// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ProjectionRoom/internal/config"
	"ProjectionRoom/internal/handler"
	"ProjectionRoom/internal/service"
	"ProjectionRoom/internal/usecase"
)

// Injectors from wire.go:

// InitializeApp 组装整个应用。
//
// 约定：
//   - 每个依赖都由它所在层的 NewXxx 提供，这里只声明装配关系；
//   - 生成结果 cmd/wire_gen.go **由 `go tool wire ./cmd` 产出，不要手写**；
//   - 依赖方向固定为 handler → usecase → model，基础设施（service）经 wire.Bind 绑到用例的接口上。
func InitializeApp(cfg *config.Config) (*Init, func(), error) {
	hub, cleanup, err := service.NewHub(cfg)
	if err != nil {
		return nil, nil, err
	}
	manager := usecase.NewManager(cfg, hub)
	engine := handler.NewRouter(cfg, hub, manager)
	server, err := service.NewServer(cfg, engine)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	init := NewInit(server)
	return init, func() {
		cleanup()
	}, nil
}
